/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Base soundtrack, returned in search results
type SoundtrackBase struct {
	// Soundtrack unique ID
	Uid string `json:"uid,omitempty"`
	// Soundtrack title
	Title string `json:"title,omitempty"`
	// Release date
	ReleaseDate string `json:"releaseDate,omitempty"`
	// Length, in seconds
	Length int32 `json:"length,omitempty"`
}
