/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Base spacecraft class, returned in search results
type SpacecraftClassBase struct {
	// Spacecraft class unique ID
	Uid string `json:"uid,omitempty"`
	// Spacecraft class name
	Name string `json:"name,omitempty"`
	// Number of decks
	NumberOfDecks int32 `json:"numberOfDecks,omitempty"`
	// Whether it's a warp-capable spacecraft class
	WarpCapable bool `json:"warpCapable,omitempty"`
	// Whether this spacecraft class is from alternate reality
	AlternateReality bool `json:"alternateReality,omitempty"`
	// Starting period when this spacecraft class was in use
	ActiveFrom string `json:"activeFrom,omitempty"`
	// Ending period when this spacecraft class was in use
	ActiveTo string `json:"activeTo,omitempty"`
	// Main species affiliated
	Species *SpeciesHeader `json:"species,omitempty"`
	// Owner
	Owner *OrganizationHeader `json:"owner,omitempty"`
	// Operator
	Operator *OrganizationHeader `json:"operator,omitempty"`
	// Affiliation
	Affiliation *OrganizationHeader `json:"affiliation,omitempty"`
}
