/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Header video release, embedded in other objects
type VideoReleaseHeader struct {
	// Video release unique ID
	Uid string `json:"uid,omitempty"`
	// Video release title
	Title string `json:"title,omitempty"`
}
