/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Header material, embedded in other objects
type MaterialHeader struct {
	// Material unique ID
	Uid string `json:"uid,omitempty"`
	// Material name
	Name string `json:"name,omitempty"`
}
