/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Base occupations, returned in search results
type OccupationBase struct {
	// Occupation unique ID
	Uid string `json:"uid,omitempty"`
	// Occupation name
	Name string `json:"name,omitempty"`
	// Whether it's a legal occupation
	LegalOccupation bool `json:"legalOccupation,omitempty"`
	// Whether it's a medical occupation
	MedicalOccupation bool `json:"medicalOccupation,omitempty"`
	// Whether it's a scientific occupation
	ScientificOccupation bool `json:"scientificOccupation,omitempty"`
}
