/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Rating of video release, etc.
type ContentRating struct {
	// Rating unique ID
	Uid string `json:"uid,omitempty"`
	// Content rating system
	ContentRatingSystem *ContentRatingSystem `json:"contentRatingSystem,omitempty"`
	// Rating within specified content rating system
	Rating string `json:"rating,omitempty"`
}
