/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Full astronomical object, returned when queried using UID
type AstronomicalObjectFull struct {
	// Astronomical object's unique ID
	Uid string `json:"uid,omitempty"`
	// Astronomical object name
	Name string `json:"name,omitempty"`
	// Type of astronomical object
	AstronomicalObjectType *AstronomicalObjectType `json:"astronomicalObjectType,omitempty"`
	// Location of astronomical object (optional)
	Location *AstronomicalObjectBase `json:"location,omitempty"`
	// Astronomical objects located in this astronomical object, like planets in a star system
	AstronomicalObjects []AstronomicalObjectBase `json:"astronomicalObjects,omitempty"`
}
