/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Header occupation, embedded in other objects
type OccupationHeader struct {
	// Occupation unique ID
	Uid string `json:"uid,omitempty"`
	// Occupation name
	Name string `json:"name,omitempty"`
}
