/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Header book, embedded in other objects
type BookHeader struct {
	// Book unique ID
	Uid string `json:"uid,omitempty"`
	// Book title
	Title string `json:"title,omitempty"`
}
