/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Header staff, embedded in other objects
type StaffHeader struct {
	// Staff unique ID
	Uid string `json:"uid,omitempty"`
	// Staff name
	Name string `json:"name,omitempty"`
}
