/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Base literature, returned in search results
type LiteratureBase struct {
	// Literature unique ID
	Uid string `json:"uid,omitempty"`
	// Literature title
	Title string `json:"title,omitempty"`
	// Whether it's of earthly origin
	EarthlyOrigin bool `json:"earthlyOrigin,omitempty"`
	// Whether it's a Shakespearean work
	ShakespeareanWork bool `json:"shakespeareanWork,omitempty"`
	// Whether it's a report
	Report bool `json:"report,omitempty"`
	// Whether it's a scientific literature
	ScientificLiterature bool `json:"scientificLiterature,omitempty"`
	// Whether it's a technical manual
	TechnicalManual bool `json:"technicalManual,omitempty"`
	// Whether it's a religious literature
	ReligiousLiterature bool `json:"religiousLiterature,omitempty"`
}
