/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Header title, embedded in other objects
type TitleHeader struct {
	// Title unique ID
	Uid string `json:"uid,omitempty"`
	// Title name
	Name string `json:"name,omitempty"`
}
