/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Full comic strip, returned when queried using UID
type ComicStripFull struct {
	// Comic strip unique ID
	Uid string `json:"uid,omitempty"`
	// Comic strip title
	Title string `json:"title,omitempty"`
	// Title of the periodical the comic strip was published in
	Periodical string `json:"periodical,omitempty"`
	// Year from which the comic strip was published
	PublishedYearFrom int32 `json:"publishedYearFrom,omitempty"`
	// Month from which the comic strip was published
	PublishedMonthFrom int32 `json:"publishedMonthFrom,omitempty"`
	// Day from which the comic strip was published
	PublishedDayFrom int32 `json:"publishedDayFrom,omitempty"`
	// Year to which the comic strip was published
	PublishedYearTo int32 `json:"publishedYearTo,omitempty"`
	// Month to which the comic strip was published
	PublishedMonthTo int32 `json:"publishedMonthTo,omitempty"`
	// Day to which the comic strip was published
	PublishedDayTo int32 `json:"publishedDayTo,omitempty"`
	// Number of pages
	NumberOfPages int32 `json:"numberOfPages,omitempty"`
	// Starting year of comic strip stories
	YearFrom int32 `json:"yearFrom,omitempty"`
	// Ending year of comic strip stories
	YearTo int32 `json:"yearTo,omitempty"`
	// Comic series this comic strip is included in
	ComicSeries []ComicSeriesBase `json:"comicSeries,omitempty"`
	// Writers involved in the comic strip
	Writers []StaffBase `json:"writers,omitempty"`
	// Artists involved in the comic strip
	Artists []StaffBase `json:"artists,omitempty"`
	// Characters appearing in the comic strip
	Characters []CharacterBase `json:"characters,omitempty"`
}
