/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Full episode, returned when queried using UID
type EpisodeFull struct {
	// Episode unique ID
	Uid string `json:"uid,omitempty"`
	// Episode title
	Title string `json:"title,omitempty"`
	// Episode title in German
	TitleGerman string `json:"titleGerman,omitempty"`
	// Episode title in Italian
	TitleItalian string `json:"titleItalian,omitempty"`
	// Episode title in Japanese
	TitleJapanese string `json:"titleJapanese,omitempty"`
	// Series this episode belongs to
	Series *SeriesBase `json:"series,omitempty"`
	// Season this episode belongs to
	Season *SeasonBase `json:"season,omitempty"`
	// Season number
	SeasonNumber int32 `json:"seasonNumber,omitempty"`
	// Episode number in season
	EpisodeNumber int32 `json:"episodeNumber,omitempty"`
	// Production serial number
	ProductionSerialNumber string `json:"productionSerialNumber,omitempty"`
	// Whether it's a feature length episode
	FeatureLength bool `json:"featureLength,omitempty"`
	// Starting stardate of episode story
	StardateFrom float32 `json:"stardateFrom,omitempty"`
	// Ending stardate of episode story
	StardateTo float32 `json:"stardateTo,omitempty"`
	// Starting year of episode story
	YearFrom int32 `json:"yearFrom,omitempty"`
	// Ending year of episode story
	YearTo int32 `json:"yearTo,omitempty"`
	// Date the episode was first aired in the United States
	UsAirDate string `json:"usAirDate,omitempty"`
	// Date the episode script was completed
	FinalScriptDate string `json:"finalScriptDate,omitempty"`
	// Writers involved in the episode
	Writers []StaffBase `json:"writers,omitempty"`
	// Teleplay authors involved in the episode
	TeleplayAuthors []StaffBase `json:"teleplayAuthors,omitempty"`
	// Story authors involved in the episode
	StoryAuthors []StaffBase `json:"storyAuthors,omitempty"`
	// Directors authors involved in the episode
	Directors []StaffBase `json:"directors,omitempty"`
	// Performers appearing in the episode
	Performers []PerformerBase `json:"performers,omitempty"`
	// Stunt performers appearing in the episode
	StuntPerformers []PerformerBase `json:"stuntPerformers,omitempty"`
	// Stand-in performers appearing in the episode
	StandInPerformers []PerformerBase `json:"standInPerformers,omitempty"`
	// Characters appearing in the episode
	Characters []CharacterBase `json:"characters,omitempty"`
}
