/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Full comic collection, returned when queried using UID
type ComicCollectionFull struct {
	// Comic collection unique ID
	Uid string `json:"uid,omitempty"`
	// Comic collection title
	Title string `json:"title,omitempty"`
	// Year the comic collection was published
	PublishedYear int32 `json:"publishedYear,omitempty"`
	// Month the comic collection was published
	PublishedMonth int32 `json:"publishedMonth,omitempty"`
	// Day the comic collection was published
	PublishedDay int32 `json:"publishedDay,omitempty"`
	// Cover publication year
	CoverYear int32 `json:"coverYear,omitempty"`
	// Cover publication month
	CoverMonth int32 `json:"coverMonth,omitempty"`
	// Cover publication day
	CoverDay int32 `json:"coverDay,omitempty"`
	// Number of pages
	NumberOfPages int32 `json:"numberOfPages,omitempty"`
	// Starting stardate of comic collection stories
	StardateFrom float32 `json:"stardateFrom,omitempty"`
	// Ending stardate of comic collection stories
	StardateTo float32 `json:"stardateTo,omitempty"`
	// Starting year of comic collection stories
	YearFrom int32 `json:"yearFrom,omitempty"`
	// Ending year of comic collection stories
	YearTo int32 `json:"yearTo,omitempty"`
	// Whether it's a photonovel collection
	Photonovel bool `json:"photonovel,omitempty"`
	// Comic series this comic collection is included in
	ComicSeries []ComicSeriesBase `json:"comicSeries,omitempty"`
	// Writers involved in the comic collection
	Writers []StaffBase `json:"writers,omitempty"`
	// Artists involved in the comic collection
	Artists []StaffBase `json:"artists,omitempty"`
	// Editors involved in the comic collection
	Editors []StaffBase `json:"editors,omitempty"`
	// Other staff involved in the comic collection
	Staff []StaffBase `json:"staff,omitempty"`
	// Comic collection publishers
	Publishers []CompanyBase `json:"publishers,omitempty"`
	// Characters appearing in the comic collection
	Characters []CharacterBase `json:"characters,omitempty"`
	// References
	References []Reference `json:"references,omitempty"`
	// Comics included in this comic collection
	Comics []ComicsBase `json:"comics,omitempty"`
}
