/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Base title, returned in search results
type TitleBase struct {
	// Title unique ID
	Uid string `json:"uid,omitempty"`
	// Title name
	Name string `json:"name,omitempty"`
	// Whether it's a military rank
	MilitaryRank bool `json:"militaryRank,omitempty"`
	// Whether it's a fleet rank
	FleetRank bool `json:"fleetRank,omitempty"`
	// Whether it's a religious title
	ReligiousTitle bool `json:"religiousTitle,omitempty"`
	// Whether it's a position
	Position bool `json:"position,omitempty"`
	// Whether this title is from mirror universe
	Mirror bool `json:"mirror,omitempty"`
}
