/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Full book collection, returned when queried using UID
type BookCollectionFull struct {
	// Book collection unique ID
	Uid string `json:"uid,omitempty"`
	// Book collection title
	Title string `json:"title,omitempty"`
	// Year the book collection was published
	PublishedYear int32 `json:"publishedYear,omitempty"`
	// Month the book collection was published
	PublishedMonth int32 `json:"publishedMonth,omitempty"`
	// Day the book collection was published
	PublishedDay int32 `json:"publishedDay,omitempty"`
	// Number of pages
	NumberOfPages int32 `json:"numberOfPages,omitempty"`
	// Starting stardate of book collection stories
	StardateFrom float32 `json:"stardateFrom,omitempty"`
	// Ending stardate of book collection stories
	StardateTo float32 `json:"stardateTo,omitempty"`
	// Starting year of book collection stories
	YearFrom int32 `json:"yearFrom,omitempty"`
	// Ending year of book collection stories
	YearTo int32 `json:"yearTo,omitempty"`
	// Book series this book collection is included in
	BookSeries []BookSeriesBase `json:"bookSeries,omitempty"`
	// Authors of the book collection
	Authors []StaffBase `json:"authors,omitempty"`
	// Artists involved in the book collection
	Artists []StaffBase `json:"artists,omitempty"`
	// Editors involved in the book collection
	Editors []StaffBase `json:"editors,omitempty"`
	// Book collection publishers
	Publishers []CompanyBase `json:"publishers,omitempty"`
	// Characters appearing in the book collection
	Characters []CharacterBase `json:"characters,omitempty"`
	// References
	References []Reference `json:"references,omitempty"`
	// Books included in this book collection
	Books []BookBase `json:"books,omitempty"`
}
