/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Full character, returned when queried using UID
type CharacterFull struct {
	// Character unique ID
	Uid string `json:"uid,omitempty"`
	// Character name
	Name string `json:"name,omitempty"`
	// Character gender
	Gender *Gender `json:"gender,omitempty"`
	// Year the character was born
	YearOfBirth int32 `json:"yearOfBirth,omitempty"`
	// Month the character was born
	MonthOfBirth int32 `json:"monthOfBirth,omitempty"`
	// Day the character was born
	DayOfBirth int32 `json:"dayOfBirth,omitempty"`
	// Place of birth
	PlaceOfBirth string `json:"placeOfBirth,omitempty"`
	// Year the character died
	YearOfDeath int32 `json:"yearOfDeath,omitempty"`
	// Month the character died
	MonthOfDeath int32 `json:"monthOfDeath,omitempty"`
	// Day the character died
	DayOfDeath int32 `json:"dayOfDeath,omitempty"`
	// Place of death
	PlaceOfDeath string `json:"placeOfDeath,omitempty"`
	// Height in centimeters
	Height int32 `json:"height,omitempty"`
	// Weight in kilograms
	Weight int32 `json:"weight,omitempty"`
	// Whether this character is deceased
	Deceased bool `json:"deceased,omitempty"`
	// Blood type
	BloodType *BloodType `json:"bloodType,omitempty"`
	// Marital status
	MaritalStatus *MaritalStatus `json:"maritalStatus,omitempty"`
	// Serial number
	SerialNumber string `json:"serialNumber,omitempty"`
	// Hologram activation date
	HologramActivationDate string `json:"hologramActivationDate,omitempty"`
	// Hologram status
	HologramStatus string `json:"hologramStatus,omitempty"`
	// Hologram date status
	HologramDateStatus string `json:"hologramDateStatus,omitempty"`
	// Whether this character is a hologram
	Hologram bool `json:"hologram,omitempty"`
	// Whether this character is a fictional character (from universe point of view)
	FictionalCharacter bool `json:"fictionalCharacter,omitempty"`
	// Whether this character is from mirror universe
	Mirror bool `json:"mirror,omitempty"`
	// Whether this character is from alternate reality
	AlternateReality bool `json:"alternateReality,omitempty"`
	// Performers who played this character
	Performers []PerformerBase `json:"performers,omitempty"`
	// Episodes in which this character appeared
	Episodes []EpisodeBase `json:"episodes,omitempty"`
	// Movies in which this character appeared
	Movies []MovieBase `json:"movies,omitempty"`
	// Species this character belongs to
	CharacterSpecies []CharacterSpecies `json:"characterSpecies,omitempty"`
	// Relations with other characters
	CharacterRelations []CharacterRelation `json:"characterRelations,omitempty"`
	// Titles this character holds
	Titles []TitleBase `json:"titles,omitempty"`
	// Occupations of this character
	Occupations []OccupationBase `json:"occupations,omitempty"`
	// Organizations this character has affiliation with
	Organizations []OrganizationBase `json:"organizations,omitempty"`
}
