/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Response object for single technology query
type TechnologyFullResponse struct {
	// Technology, if found
	Technology *TechnologyFull `json:"technology,omitempty"`
}
