/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Base season, returned in search results
type SeasonBase struct {
	// Season unique ID
	Uid string `json:"uid,omitempty"`
	// Season title
	Title string `json:"title,omitempty"`
	// Series this season belongs to
	Series *SeriesHeader `json:"series,omitempty"`
	// Season number in series
	SeasonNumber int32 `json:"seasonNumber,omitempty"`
	// Number of episodes in this season
	NumberOfEpisodes int32 `json:"numberOfEpisodes,omitempty"`
}
