/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Rating of video release, etc.
type ContentLanguage struct {
	// Language unique ID
	Uid string `json:"uid,omitempty"`
	// Language name
	Name string `json:"name,omitempty"`
	// ISO 639-1 code
	Iso6391Code string `json:"iso6391Code,omitempty"`
}
