/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Base spacecraft, returned in search results
type SpacecraftBase struct {
	// Spacecraft unique ID
	Uid string `json:"uid,omitempty"`
	// Spacecraft name
	Name string `json:"name,omitempty"`
	// Spacecraft registry
	Registry string `json:"registry,omitempty"`
	// Status of a spacecraft (in prime reality, if spacecraft was in more than one realities)
	Status string `json:"status,omitempty"`
	// Date the spacecraft status was last known
	DateStatus string `json:"dateStatus,omitempty"`
	// Spacecraft class
	SpacecraftClass *SpacecraftClassHeader `json:"spacecraftClass,omitempty"`
	// Owner
	Owner *OrganizationHeader `json:"owner,omitempty"`
	// Operator
	Operator *OrganizationHeader `json:"operator,omitempty"`
}
