/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Header location, embedded in other objects
type LocationHeader struct {
	// Location unique ID
	Uid string `json:"uid,omitempty"`
	// Location name
	Name string `json:"name,omitempty"`
}
