/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Reference of book, comics, video release, etc.
type Reference struct {
	Uid string `json:"uid,omitempty"`
	ReferenceType *ReferenceType `json:"referenceType,omitempty"`
	ReferenceNumber string `json:"referenceNumber,omitempty"`
}
