/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Genre of video games
type Genre struct {
	// Genre unique ID
	Uid string `json:"uid,omitempty"`
	// Genre name
	Name string `json:"name,omitempty"`
}
