/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Base book, returned in search results
type BookBase struct {
	// Book unique ID
	Uid string `json:"uid,omitempty"`
	// Book title
	Title string `json:"title,omitempty"`
	// Year the book was published
	PublishedYear int32 `json:"publishedYear,omitempty"`
	// Month the book was published
	PublishedMonth int32 `json:"publishedMonth,omitempty"`
	// Day the book was published
	PublishedDay int32 `json:"publishedDay,omitempty"`
	// Number of pages
	NumberOfPages int32 `json:"numberOfPages,omitempty"`
	// Starting stardate of book story
	StardateFrom float32 `json:"stardateFrom,omitempty"`
	// Ending stardate of book story
	StardateTo float32 `json:"stardateTo,omitempty"`
	// Starting year of book story
	YearFrom int32 `json:"yearFrom,omitempty"`
	// Ending year of book story
	YearTo int32 `json:"yearTo,omitempty"`
	// Whether it's a novel
	Novel bool `json:"novel,omitempty"`
	// Whether it's a reference book
	ReferenceBook bool `json:"referenceBook,omitempty"`
	// Whether it's a biography book
	BiographyBook bool `json:"biographyBook,omitempty"`
	// Whether it's a role playing book
	RolePlayingBook bool `json:"rolePlayingBook,omitempty"`
	// Whether it's an eBook
	EBook bool `json:"eBook,omitempty"`
	// Whether it's an anthology
	Anthology bool `json:"anthology,omitempty"`
	// Whether it's a novelization
	Novelization bool `json:"novelization,omitempty"`
	// Whether it's an audiobook, or has been release as an audiobook in addition to other form
	Audiobook bool `json:"audiobook,omitempty"`
	// If it's an audiobook, whether it's been abridged
	AudiobookAbridged bool `json:"audiobookAbridged,omitempty"`
	// Year the audiobook was published
	AudiobookPublishedYear int32 `json:"audiobookPublishedYear,omitempty"`
	// Month the audiobook was published
	AudiobookPublishedMonth int32 `json:"audiobookPublishedMonth,omitempty"`
	// Day the audiobook was published
	AudiobookPublishedDay int32 `json:"audiobookPublishedDay,omitempty"`
	// Audiobook run time, in minutes
	AudiobookRunTime int32 `json:"audiobookRunTime,omitempty"`
	// Book's production number
	ProductionNumber string `json:"productionNumber,omitempty"`
}
