/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Response object for single trading card deck query
type TradingCardDeckFullResponse struct {
	// Trading card deck, if found
	TradingCardDeck *TradingCardDeckFull `json:"tradingCardDeck,omitempty"`
}
