/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Header trading card set, embedded in other objects
type TradingCardSetHeader struct {
	// Trading card set unique ID
	Uid string `json:"uid,omitempty"`
	// Trading card set name
	Name string `json:"name,omitempty"`
}
