/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Base material, returned in search results
type MaterialBase struct {
	// Material unique ID
	Uid string `json:"uid,omitempty"`
	// Material name
	Name string `json:"name,omitempty"`
	// Whether it's a chemical compound
	ChemicalCompound bool `json:"chemicalCompound,omitempty"`
	// Whether it's a biochemical compound
	BiochemicalCompound bool `json:"biochemicalCompound,omitempty"`
	// Whether it's a drug
	Drug bool `json:"drug,omitempty"`
	// Whether it's a poisonous substance
	PoisonousSubstance bool `json:"poisonousSubstance,omitempty"`
	// Whether it's an explosive
	Explosive bool `json:"explosive,omitempty"`
	// Whether it's a gemstone
	Gemstone bool `json:"gemstone,omitempty"`
	// Whether it's an alloy or a composite
	AlloyOrComposite bool `json:"alloyOrComposite,omitempty"`
	// Whether it's a fuel
	Fuel bool `json:"fuel,omitempty"`
	// Whether it's a mineral
	Mineral bool `json:"mineral,omitempty"`
	// Whether it's a precious material
	PreciousMaterial bool `json:"preciousMaterial,omitempty"`
}
