/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Full medical condition, returned when queried using UID
type MedicalConditionFull struct {
	// Medical condition unique ID
	Uid string `json:"uid,omitempty"`
	// Medical condition name
	Name string `json:"name,omitempty"`
	// Whether it's a psychological condition
	PsychologicalCondition bool `json:"psychologicalCondition,omitempty"`
}
