/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Header magazine, embedded in other objects
type MagazineHeader struct {
	// Magazine unique ID
	Uid string `json:"uid,omitempty"`
	// Magazine title
	Title string `json:"title,omitempty"`
}
