/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Header food, embedded in other objects
type FoodHeader struct {
	// Food unique ID
	Uid string `json:"uid,omitempty"`
	// Food name
	Name string `json:"name,omitempty"`
}
