/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi
// AstronomicalObjectType : Astronomical object type
type AstronomicalObjectType string

// List of AstronomicalObjectType
const (
	PLANET_AstronomicalObjectType AstronomicalObjectType = "PLANET"
	D_CLASS_PLANET_AstronomicalObjectType AstronomicalObjectType = "D_CLASS_PLANET"
	H_CLASS_PLANET_AstronomicalObjectType AstronomicalObjectType = "H_CLASS_PLANET"
	GAS_GIANT_PLANET_AstronomicalObjectType AstronomicalObjectType = "GAS_GIANT_PLANET"
	K_CLASS_PLANET_AstronomicalObjectType AstronomicalObjectType = "K_CLASS_PLANET"
	L_CLASS_PLANET_AstronomicalObjectType AstronomicalObjectType = "L_CLASS_PLANET"
	M_CLASS_PLANET_AstronomicalObjectType AstronomicalObjectType = "M_CLASS_PLANET"
	Y_CLASS_PLANET_AstronomicalObjectType AstronomicalObjectType = "Y_CLASS_PLANET"
	ROGUE_PLANET_AstronomicalObjectType AstronomicalObjectType = "ROGUE_PLANET"
	ARTIFICIAL_PLANET_AstronomicalObjectType AstronomicalObjectType = "ARTIFICIAL_PLANET"
	ASTEROID_AstronomicalObjectType AstronomicalObjectType = "ASTEROID"
	ASTEROIDAL_MOON_AstronomicalObjectType AstronomicalObjectType = "ASTEROIDAL_MOON"
	ASTEROID_BELT_AstronomicalObjectType AstronomicalObjectType = "ASTEROID_BELT"
	CLUSTER_AstronomicalObjectType AstronomicalObjectType = "CLUSTER"
	COMET_AstronomicalObjectType AstronomicalObjectType = "COMET"
	CONSTELLATION_AstronomicalObjectType AstronomicalObjectType = "CONSTELLATION"
	GALAXY_AstronomicalObjectType AstronomicalObjectType = "GALAXY"
	MOON_AstronomicalObjectType AstronomicalObjectType = "MOON"
	M_CLASS_MOON_AstronomicalObjectType AstronomicalObjectType = "M_CLASS_MOON"
	NEBULA_AstronomicalObjectType AstronomicalObjectType = "NEBULA"
	PLANETOID_AstronomicalObjectType AstronomicalObjectType = "PLANETOID"
	D_CLASS_PLANETOID_AstronomicalObjectType AstronomicalObjectType = "D_CLASS_PLANETOID"
	QUASAR_AstronomicalObjectType AstronomicalObjectType = "QUASAR"
	STAR_AstronomicalObjectType AstronomicalObjectType = "STAR"
	STAR_SYSTEM_AstronomicalObjectType AstronomicalObjectType = "STAR_SYSTEM"
	SECTOR_AstronomicalObjectType AstronomicalObjectType = "SECTOR"
	REGION_AstronomicalObjectType AstronomicalObjectType = "REGION"
)
