/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Full trading card deck, returned when queried using UID
type TradingCardDeckFull struct {
	// Trading card deck unique ID
	Uid string `json:"uid,omitempty"`
	// Trading card deck name
	Name string `json:"name,omitempty"`
	// Frequency with which this deck occur in it's set
	Frequency string `json:"frequency,omitempty"`
	// Trading card set this deck belongs to
	TradingCardSet *TradingCardSetHeader `json:"tradingCardSet,omitempty"`
	// Trading cards in this deck
	TradingCards []TradingCardBase `json:"tradingCards,omitempty"`
}
