/*
 * STAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stapi

// Object describing response page
type ResponsePage struct {
	// Zero-based page number
	PageNumber int32 `json:"pageNumber,omitempty"`
	// Page size
	PageSize int32 `json:"pageSize,omitempty"`
	// Number of elements in page
	NumberOfElements int32 `json:"numberOfElements,omitempty"`
	// Total elements found
	TotalElements int32 `json:"totalElements,omitempty"`
	// Total pages found
	TotalPages int32 `json:"totalPages,omitempty"`
	// Whether it is the first page
	FirstPage bool `json:"firstPage,omitempty"`
	// Whether it is the last page
	LastPage bool `json:"lastPage,omitempty"`
}
